/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public class CadastrarItem extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarItem
     */
    private static CadastrarItem janelaControl;
    
    public CadastrarItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCategoria = new javax.swing.JLabel();
        jLabelCadastrar1 = new javax.swing.JLabel();
        jTextFieldNomeDescrição = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelDataDescrição = new javax.swing.JLabel();
        jLabelNomeItem1 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxAno = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabelDataPerda1 = new javax.swing.JLabel();
        jTextFieldNomeItem1 = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jLabelFundoCadastrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setText("Categoria:");
        getContentPane().add(jLabelCategoria);
        jLabelCategoria.setBounds(30, 170, 110, 30);

        jLabelCadastrar1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastrar1.setText("Cadastrar Item");
        getContentPane().add(jLabelCadastrar1);
        jLabelCadastrar1.setBounds(280, 0, 280, 70);
        getContentPane().add(jTextFieldNomeDescrição);
        jTextFieldNomeDescrição.setBounds(210, 280, 450, 170);

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(330, 510, 150, 40);

        jLabelDataDescrição.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDataDescrição.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataDescrição.setText("Descrição:");
        getContentPane().add(jLabelDataDescrição);
        jLabelDataDescrição.setBounds(30, 270, 180, 30);

        jLabelNomeItem1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNomeItem1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeItem1.setText("Nome do item:");
        getContentPane().add(jLabelNomeItem1);
        jLabelNomeItem1.setBounds(30, 120, 170, 29);

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxDia);
        jComboBoxDia.setBounds(210, 220, 60, 30);

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxMes);
        jComboBoxMes.setBounds(290, 220, 60, 30);

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxAno);
        jComboBoxAno.setBounds(380, 220, 60, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(210, 170, 200, 30);

        jLabelDataPerda1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDataPerda1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataPerda1.setText("Data de perda:");
        getContentPane().add(jLabelDataPerda1);
        jLabelDataPerda1.setBounds(30, 220, 180, 30);
        getContentPane().add(jTextFieldNomeItem1);
        jTextFieldNomeItem1.setBounds(210, 120, 200, 30);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(20, 530, 73, 23);

        jLabelFundoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fundo2.png"))); // NOI18N
        jLabelFundoCadastrar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fundo2.png"))); // NOI18N
        jLabelFundoCadastrar.setEnabled(false);
        getContentPane().add(jLabelFundoCadastrar);
        jLabelFundoCadastrar.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        JOptionPane.showConfirmDialog(null, "Deseja confirmar o cadastro?");
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       janelaControl.dispose();
       TelaPrincipalAdm telaPrincipal = new TelaPrincipalAdm();
       telaPrincipal.mostrar();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mostrar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarItem cadastrarItem = new CadastrarItem();
                cadastrarItem.setVisible(true);
                janelaControl = cadastrarItem;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBoxAno;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabelCadastrar1;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDataDescrição;
    private javax.swing.JLabel jLabelDataPerda1;
    private javax.swing.JLabel jLabelFundoCadastrar;
    private javax.swing.JLabel jLabelNomeItem1;
    private javax.swing.JTextField jTextFieldNomeDescrição;
    private javax.swing.JTextField jTextFieldNomeItem1;
    // End of variables declaration//GEN-END:variables

}
