/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.net.Socket;
import model.Item;
import model.SGBD;
import model.Sockets;

/**
 *
 * @author ld_si
 */
public class Requerimento extends javax.swing.JFrame {

    private static Requerimento janelaControl;
    private static Socket cliente;
    private static Item item;

    /**
     * Creates new form Requerimento
     */
    public Requerimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAceitar = new javax.swing.JButton();
        jButtonNegar = new javax.swing.JButton();
        jLabelNomeItem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelLogoFindesk = new javax.swing.JLabel();
        jScrollPaneDescricao = new javax.swing.JScrollPane();
        jTextDescricao = new javax.swing.JTextArea();
        jLabelId = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Requerimento");
        jPanelFundo.add(jLabelTitulo);
        jLabelTitulo.setBounds(20, 120, 260, 70);

        jButtonAceitar.setText("Aceitar");
        jButtonAceitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceitarActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonAceitar);
        jButtonAceitar.setBounds(520, 510, 90, 32);

        jButtonNegar.setText("Negar");
        jButtonNegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegarActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonNegar);
        jButtonNegar.setBounds(220, 510, 90, 32);

        jLabelNomeItem.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeItem.setText("Nome:");
        jPanelFundo.add(jLabelNomeItem);
        jLabelNomeItem.setBounds(30, 210, 330, 16);
        jPanelFundo.add(jSeparator1);
        jSeparator1.setBounds(0, 110, 800, 20);

        jLabelLogoFindesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/FINDESK_LOGO3_PNG.png"))); // NOI18N
        jPanelFundo.add(jLabelLogoFindesk);
        jLabelLogoFindesk.setBounds(-40, -10, 350, 110);

        jTextDescricao.setColumns(20);
        jTextDescricao.setRows(5);
        jScrollPaneDescricao.setViewportView(jTextDescricao);

        jPanelFundo.add(jScrollPaneDescricao);
        jScrollPaneDescricao.setBounds(10, 310, 780, 160);

        jLabelId.setForeground(new java.awt.Color(0, 0, 0));
        jLabelId.setText("ID:");
        jPanelFundo.add(jLabelId);
        jLabelId.setBounds(30, 190, 220, 16);

        jLabelCor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCor.setText("Cor:");
        jPanelFundo.add(jLabelCor);
        jLabelCor.setBounds(30, 230, 220, 16);

        jLabelData.setForeground(new java.awt.Color(0, 0, 0));
        jLabelData.setText("Data:");
        jPanelFundo.add(jLabelData);
        jLabelData.setBounds(30, 250, 210, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceitarActionPerformed
             
        Sockets.sendText(cliente, "Aceito");
        
        janelaControl.dispose();
        
    }//GEN-LAST:event_jButtonAceitarActionPerformed

    private void jButtonNegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegarActionPerformed
 
        Sockets.sendText(cliente, "Negado");
        janelaControl.setVisible(false);
    }//GEN-LAST:event_jButtonNegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mostrar(Socket novoCliente, Item novoItem) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requerimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requerimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requerimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requerimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Requerimento janela = new Requerimento();
                jLabelNomeItem.setText("Nome: " + novoItem.getNomeItem());
                item = novoItem;
                janela.setVisible(true);
                janela.setAlwaysOnTop(true);
                janelaControl = janela;
                cliente = novoCliente;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceitar;
    private javax.swing.JButton jButtonNegar;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLogoFindesk;
    private static javax.swing.JLabel jLabelNomeItem;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JScrollPane jScrollPaneDescricao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextDescricao;
    // End of variables declaration//GEN-END:variables
}
