/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



/**
 *
 * @author alvar
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    private static TelaPrincipal janelaControl; 
    
            
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelLogoFindesk = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelFechar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        setResizable(false);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setLayout(null);

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanelFundo.add(jSeparator2);
        jSeparator2.setBounds(0, 500, 800, 30);

        jLabelLogoFindesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/FINDESK_LOGO3_PNG.png"))); // NOI18N
        jPanelFundo.add(jLabelLogoFindesk);
        jLabelLogoFindesk.setBounds(210, 0, 410, 160);

        jButtonCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCadastrar.setText("Cadastrar Item");
        jButtonCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonCadastrar);
        jButtonCadastrar.setBounds(270, 330, 260, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/SWS3.png"))); // NOI18N
        jPanelFundo.add(jLabel1);
        jLabel1.setBounds(690, 500, 170, 220);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanelFundo.add(jSeparator1);
        jSeparator1.setBounds(10, 150, 800, 30);

        jLabelFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-excluir-24.png"))); // NOI18N
        jLabelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFecharMouseClicked(evt);
            }
        });
        jPanelFundo.add(jLabelFechar);
        jLabelFechar.setBounds(760, 0, 30, 40);

        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-minimize-window-24.png"))); // NOI18N
        jPanelFundo.add(jLabelMinimizar);
        jLabelMinimizar.setBounds(710, 10, 30, 20);

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanelFundo.add(jButtonBuscar);
        jButtonBuscar.setBounds(270, 230, 260, 60);

        getContentPane().add(jPanelFundo);
        jPanelFundo.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(799, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        janelaControl.dispose();
        CadastrarItem cadastrarItem = new CadastrarItem();
        CadastrarItem.mostrar();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved

    private void jLabelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelFecharMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        janelaControl.dispose();
         BuscarAdministrador buscaTeste = new BuscarAdministrador();
         buscaTeste.mostrar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     */
    public static void mostrar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
               TelaPrincipal telaPrincipal =  new TelaPrincipal();
               telaPrincipal.setVisible(true);
               janelaControl = telaPrincipal;
            }
        });
    }
                
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFechar;
    private javax.swing.JLabel jLabelLogoFindesk;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
