/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author alvar
 */
public class Estatisticas extends javax.swing.JFrame {

    /**
     * Creates new form userInterface
     */
    public Estatisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        checkBoxVestiveis = new javax.swing.JCheckBox();
        checkBoxEletronicos = new javax.swing.JCheckBox();
        labelCategoria = new javax.swing.JLabel();
        labelEstadoItem = new javax.swing.JLabel();
        labelTituloEstatistica = new javax.swing.JLabel();
        checkBoxResgatados = new javax.swing.JCheckBox();
        checkBoxPerdidos = new javax.swing.JCheckBox();
        checkBoxTodas = new javax.swing.JCheckBox();
        checkBoxRecipientes = new javax.swing.JCheckBox();
        buttonGerar = new javax.swing.JButton();
        checkBoxMateriais = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        labelPlanoFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        checkBoxVestiveis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxVestiveis.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxVestiveis.setText("Vestivéis");
        getContentPane().add(checkBoxVestiveis);
        checkBoxVestiveis.setBounds(400, 320, 140, 30);

        checkBoxEletronicos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxEletronicos.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxEletronicos.setText("Eletrônicos");
        getContentPane().add(checkBoxEletronicos);
        checkBoxEletronicos.setBounds(220, 320, 140, 30);

        labelCategoria.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        labelCategoria.setText("Categorias");
        getContentPane().add(labelCategoria);
        labelCategoria.setBounds(30, 270, 200, 40);

        labelEstadoItem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEstadoItem.setForeground(new java.awt.Color(255, 255, 255));
        labelEstadoItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEstadoItem.setText("Estado do Item ");
        getContentPane().add(labelEstadoItem);
        labelEstadoItem.setBounds(30, 150, 200, 40);

        labelTituloEstatistica.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTituloEstatistica.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloEstatistica.setText("Estatisticas");
        getContentPane().add(labelTituloEstatistica);
        labelTituloEstatistica.setBounds(290, 40, 220, 50);

        checkBoxResgatados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxResgatados.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxResgatados.setText("Resgatado");
        getContentPane().add(checkBoxResgatados);
        checkBoxResgatados.setBounds(220, 200, 140, 30);

        checkBoxPerdidos.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPerdidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxPerdidos.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPerdidos.setText("Perdido");
        getContentPane().add(checkBoxPerdidos);
        checkBoxPerdidos.setBounds(30, 200, 140, 30);

        checkBoxTodas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxTodas.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxTodas.setText("Todas");
        getContentPane().add(checkBoxTodas);
        checkBoxTodas.setBounds(30, 320, 140, 30);

        checkBoxRecipientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxRecipientes.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxRecipientes.setText("Recipientes");
        getContentPane().add(checkBoxRecipientes);
        checkBoxRecipientes.setBounds(580, 320, 140, 30);

        buttonGerar.setText("Gerar Estatísticas");
        buttonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGerarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGerar);
        buttonGerar.setBounds(320, 520, 150, 30);

        checkBoxMateriais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxMateriais.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxMateriais.setText("Materiais");
        getContentPane().add(checkBoxMateriais);
        checkBoxMateriais.setBounds(30, 380, 140, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Outros");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(220, 380, 140, 30);

        labelPlanoFundo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPlanoFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/telaFundo.png"))); // NOI18N
        getContentPane().add(labelPlanoFundo);
        labelPlanoFundo.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(809, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGerarActionPerformed
       Estatisticas2 tela = new Estatisticas2();
       tela.setVisible(true);
    }//GEN-LAST:event_buttonGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estatisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxEletronicos;
    private javax.swing.JCheckBox checkBoxMateriais;
    private javax.swing.JCheckBox checkBoxPerdidos;
    private javax.swing.JCheckBox checkBoxRecipientes;
    private javax.swing.JCheckBox checkBoxResgatados;
    private javax.swing.JCheckBox checkBoxTodas;
    private javax.swing.JCheckBox checkBoxVestiveis;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelEstadoItem;
    private javax.swing.JLabel labelPlanoFundo;
    private javax.swing.JLabel labelTituloEstatistica;
    // End of variables declaration//GEN-END:variables
}
