/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.sql.Array;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author ld_si
 */
public class BuscaUserImage extends javax.swing.JFrame {
    private static BuscaUserImage janelaControl;
    /**
     * Creates new form BuscaUserImage
     */
    private int qtd = 20;
    private  JLabel[] novo = new JLabel[qtd];
    
    
    public BuscaUserImage() {
        //initComponents();
        initComponent(qtd);
        //labelCreate();
        popular();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMoldura1 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabelMoldura1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabelMoldura1.setEnabled(false);
        jPanel1.add(jLabelMoldura1);
        jLabelMoldura1.setBounds(20, 20, 160, 160);

        jLabelFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabelFoto);
        jLabelFoto.setBounds(40, 40, 120, 90);

        jLabelId.setText("ID:");
        jPanel1.add(jLabelId);
        jLabelId.setBounds(40, 140, 120, 14);

        jLabelNome.setText("Nome:");
        jPanel1.add(jLabelNome);
        jLabelNome.setBounds(40, 160, 120, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 90, 660, 410);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/bt2.png"))); // NOI18N
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(70, 510, 120, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/bt2.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 510, 120, 70);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fundo2.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void initComponent(int qtd) {
       
       
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        
        int x = 50, y = 20;
        for (int i = 0; i < qtd; i++) {
            novo[i] = new JLabel();
            novo[i].setText("teste" + (i+1));
        
            getContentPane().add(novo[i]);
            novo[i].setBounds((x+8), y, 34, 14);
            x = x + 50;
            if(x >= 700){
                y = y + 20;
                x = 50;
            }
        }
        
        
        

        

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaUserImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaUserImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaUserImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaUserImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaUserImage janela = new BuscaUserImage();
                janelaControl = janela;
                janela.setVisible(true);
            }
        });
    }
    
    public void labelCreate(){
        Array[] novo = new Array[4];
        
        JLabel labels[] = new JLabel[4];
        int tx = 50,ty = 20,px = 88,py = 14;
        
        for (int i = 0; i < 4; i++) {
            labels[i].setText("label ");
            janelaControl.add(labels[i]);
            getContentPane().add(labels[i]);
            labels[i].setBounds(tx, ty, px, py);
            px += tx + 4;
        }
        
    }
    
    public void popular(){
        ImageIcon icon = new ImageIcon("C:\\Users\\ld_si\\OneDrive\\Imagens\\perfil.jpg", "teste");
        Image img = icon.getImage();
        Image nova = getScaledImage(img, 50,50);
        icon.setImage(nova);
        novo[0].setIcon(icon);
    
        
    }
    public ImageIcon criarImageIcon(String caminho, String descricao) {
        java.net.URL imgURL = getClass().getResource(caminho);
        if (imgURL != null) {
            return new ImageIcon(imgURL, descricao);
        } else {
            System.err.println("Não foi possível carregar o arquivo de imagem: " + caminho);
            return null;
        }
    }
    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();

        return resizedImg;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMoldura1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
