/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import model.SGBD;
import view.NewJFrame;

/**
 *
 * @author ld_si
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static DefaultComboBoxModel defaultComboBoxCategoria = new DefaultComboBoxModel();
    private static TelaPrincipal janelaControl;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        popularComboBox();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConfirmar = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelComboBoxCategoria = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonCriaLabel = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Findesk");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jButtonConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonConfirmar.setText("Buscar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar);
        jButtonConfirmar.setBounds(320, 450, 120, 60);

        jComboBoxCategoria.setModel(defaultComboBoxCategoria);
        jComboBoxCategoria.setSelectedItem(jComboBoxCategoria);
        getContentPane().add(jComboBoxCategoria);
        jComboBoxCategoria.setBounds(390, 200, 110, 20);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Buscar");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(320, 110, 120, 70);

        jLabelComboBoxCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComboBoxCategoria.setText("Selecionar Categoria");
        getContentPane().add(jLabelComboBoxCategoria);
        jLabelComboBoxCategoria.setBounds(240, 200, 140, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(390, 230, 110, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Inicial");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 230, 70, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(390, 260, 110, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Final");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 260, 60, 14);

        jButtonCriaLabel.setText("jButton1");
        jButtonCriaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriaLabelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCriaLabel);
        jButtonCriaLabel.setBounds(200, 320, 73, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fundo2.png"))); // NOI18N
        jLabelFundo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fundo2.png"))); // NOI18N
        jLabelFundo.setEnabled(false);
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        ocultar();
        NewJFrame novo = new NewJFrame();
        novo.criar();
        janelaControl.fechar();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCriaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriaLabelActionPerformed
        JLabel jl = new javax.swing.JLabel();
        
        jl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jl.setForeground(new java.awt.Color(255, 255, 255));
        jl.setText("teste");
        getContentPane().add(jl);
        jl.setBounds(50, 150, 50, 150);
       
    }//GEN-LAST:event_jButtonCriaLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mostrar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
                TelaPrincipal janela =  new TelaPrincipal();
                janelaControl = janela;
                janela.setVisible(true);
            }
        });
    }
    
    public static void ocultar(){
         janelaControl.setVisible(false);
    }
    
    public static void fechar(){
         janelaControl.dispose();
    }
    
    private static void popularComboBox(){
        SGBD mybd = new SGBD("127.0.0.1:3307", "findesk", "client", "client123456");
        
        mybd.getConexaoMySQL();
        ArrayList strList = new ArrayList();
        System.out.println(mybd.statusConection());
        
        
        
        ResultSet rs = mybd.consultarItemBd("SELECT * FROM categoria");
       
        String nome;
        
        try {
            rs.beforeFirst();
            while(rs.next()){
                nome = rs.getString(2);
                strList.add(nome);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        defaultComboBoxCategoria = new DefaultComboBoxModel(strList.toArray());
        
        
        mybd.fecharConexao();
        
    }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonCriaLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelComboBoxCategoria;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
